- dbcon/ddlpackage/ddl.y
The code generated by bison wouldn't compile due to the compiler finding namespace ambiguity.
> Fix DDL compile error

- dbcon/dmlpackage/calpontdmlfactory.cpp
- dbcon/dmlpackage/calpontdmlpackage.h
- dbcon/dmlpackage/commanddmlpackage.h
- dbcon/dmlpackage/deletedmlpackage.cpp
- dbcon/dmlpackage/deletedmlpackage.h
- dbcon/dmlpackage/dmlpkg.h
- dbcon/dmlpackage/insertdmlpackage.cpp
- dbcon/dmlpackage/insertdmlpackage.h
- dbcon/dmlpackage/updatedmlpackage.cpp
- dbcon/dmlpackage/updatedmlpackage.h
- dbcon/dmlpackage/vendordmlstatement.cpp
- dbcon/dmlpackage/vendordmlstatement.h
- dbcon/mysql/ha_calpont_dml.cpp
- dbcon/mysql/ha_calpont_impl_if.h
- utils/dataconvert/dataconvert.cpp
- writeengine/server/we_dmlcommandproc.cpp
NULL is now pushed through the MariaDB storage engine plugin down to the
insert processing. A '0000-00-00' date is now a separate value to NULL.
This is more in-line with MariaDB's handling.
Note: this would require MCOL-274 to land first.
> Add support for zero date separate to NULL

- dbcon/ddlpackageproc/createindexprocessor.cpp
- dbcon/ddlpackageproc/ddlpackageprocessor.cpp
- dbcon/dmlpackageproc/dmlpackageprocessor.cpp
- oam/replaytxnlog/replaytxnlog.cpp
- utils/dataconvert/dataconvert.cpp
- utils/dataconvert/dataconvert.h
- utils/funcexp/funchelpers.h
- utils/funcexp/timeextract.h
- writeengine/client/we_ddlcommandclient.cpp
- writeengine/client/we_ddlcommandclient.h
- writeengine/client/we_dmlcommandclient.cpp
- writeengine/client/we_dmlcommandclient.h
- writeengine/server/we_ddlcommandproc.cpp
- writeengine/server/we_ddlcommandproc.h
- writeengine/server/we_dmlcommandproc.cpp
- writeengine/server/we_dmlcommandproc.h
Date limit of year 1400 was used due to Boost's limits.
This patch strips out the use of Boost for date handling and sets the
lower limit to year 1000.
> Make date handling more in-line with MySQL

- dbcon/ddlpackage/ddl.y
MariaDB's parser allows for spaces instead of equals in table options, ColumnStore's parser currently does not allow this causing a query such as the following to fail:
CREATE TABLE t1 (a int, b int) ENGINE COLUMNSTORE;
This fix allows the spaces.
> Fix DDL parser for spaces in table options

- dbcon/joblist/jlf_subquery.cpp
During subquery processing it is possible to have an empty Having
clause. When this happens various tree elements are deleted but the
pointers to those tree elements are not set to NULL. So later on in
processing ExeMgr can crash.
> MCOL-240 Fix NULL handling on empty Having clause

- dbcon/mysql/ha_calpont_dml.cpp
- dbcon/mysql/ha_calpont_impl.cpp
When infinidb_use_import_for_batchinsert is enabled the NULL handling
for the batch insert was incorrect. This is due to an off-by-one on the
NULL bitmap. This also affects INSERT...SELECT.
> MCOL-173 Fix null handling for bulk inserts

- CMakeLists.txt
This puts the library in the right place, post-install creates the
symlink and the scripts run the LD_PRELOAD with it.
> Add the jemalloc install to CMake

- utils/dataconvert/dataconvert.cpp
- writeengine/bulk/we_bulkloadbuffer.cpp
- writeengine/bulk/we_tableinfo.cpp
- writeengine/splitter/we_sdhandler.cpp
Saturated DML updates would be set to NULL as were saturated cpimport
values. This sets them to the zero date/datetime value.
> MCOL-298 Fix saturated date/datetime handling

- utils/dataconvert/dataconvert.cpp
Boost::any is used for the value so it needs to be casted to a type
> Fix casting issue for date truncation

- oamapps/mcsadmin/mcsadmin.cpp
Instead of mscadmin> this changes the prompt to mcsadmin> which is in-line with the name of the utility.
> Fixes what is likely a misspelling on the mcsadmin> prompt

- utils/funcexp/funchelpers.h
The flags mask logic for the week function was incorrect. This patch
fixes it so that the behaviour is the same as MariaDB's
> MCOL-325 Fix WEEK() and YEARWEEK()

- dbcon/mysql/ha_calpont_impl.cpp
- utils/funcexp/func_date_format.cpp
- utils/funcexp/func_from_unixtime.cpp
- utils/funcexp/funcexp.cpp
Datetime has internal int value which is very different to MySQL's int
value. This patch differentiates between the two and also fixes a column
width issue which appeared once the datetime handling was fixed.
Note: there is some optimisations we can make here, but that is for another day.
> MCOL-330 Fix datetime to int conversion

- cpackEngineRPM.cmake
Using CPACK_RPM_EXCLUDE_FROM_AUTO_FILELIST_ADDITION doesn't work with
manual file lists
> Fix ignore paths for CPack so there are no conflicts

- utils/funcexp/func_add_time.cpp
In MariaDB (unlike MySQL) max/min time values include msec of 999999.
This means that subtime() with saturated values can be off by one
second.
For this calculation I have modified add_time (which also does
subtime()) to have a saturated value including 999999 msec. This fixes
the subtime test in the regression suite.
> MCOL-333 Fix subtime() for saturated values

- dbcon/mysql/ha_calpont_dml.cpp
DATETIME2 has a variable pack length but we were using a constant length
of 8 if the value was NULL. This messed up the offset for the next
column.
> MCOL-341 Fix DATETIME2 support in INSERT...SELECT

- utils/funcexp/functor_str.h
Functions such as reverse() that do float/double to string conversion
use printf's %g to do it. Unfortunately this adds a '+' symbol before
the exponent symbol. MariaDB doesn't do this.
This patch builds the string in a way that does not have that problem,
it resembles the way it is done elsewhere in the codebase.
> MCOL-328 Fix func float -> str conversion

- cpackEngineRPM.cmake
- oam/etc/ProcessConfig.xml
- oam/etc/ProcessConfig.xml.singleserver
The net-snmp that was removed also contained snmptrapd which is used by
ColumnStore. This fix makes sure the OS version is executed instead.
In addition it makes sure net-tools is installed as the 'netstat'
command is required by postConfigure
This fixes a problem mentioned in MCOL-308
> Fix snmptrad

- dbcon/mysql/ha_calpont_execplan.cpp
This was caused by Item_cache::val_str() sometimes causing a full exec of subquery before we're ready
> MCOL-46 subquery sometimes causes unknown error

- CMakeLists.txt
CMake sometimes doesn't set full rpath for the non-standard paths we
use. This patch based from CMake's manual explicitly sets it at install
time.
> MCOL-357 Set rpath correctly

- dbcon/joblist/tupleaggregatestep.cpp
It is possible for an exception to be thrown when a memory limit is hit
whilst a mutex is lock. That mutex is never unlocked and in Ubuntu 16.04
release build it can cause a crash when freed.
This patch catches the exception, releases the lock and then re-throws.
> MCOL-371 fix mutex free crash

- utils/rowgroup/rowgroup.h
It is possible to have a VARCHAR column that isn't NUL terminated, an
example of this is a union of two CHAR columns. So the length should
always act as a terminator when there is no NUL.
> MCOL-352 Fix VARCHAR with no NUL

- dbcon/joblist/jlf_execplantojoblist.cpp
If a query uses '0000-00-00' the value to compare with is hard-coded to
0. With date types there are 6 unused bits set to 1 so a zero date is
stored as 3F 00 00 00.
This removes the hard-coded setting of '0000-00-00' to 0 and uses the
correct conversion routines instead.
> MCOL-350 Fix zero date comparison

- dbcon/dmlpackage/calpontdmlpackage.cpp
- dbcon/dmlpackage/calpontdmlpackage.h
- dbcon/mysql/ha_calpont_dml.cpp
- dbcon/mysql/ha_calpont_impl.cpp
- writeengine/server/we_dmlcommandproc.cpp
This changes the warning for truncation to the correct MariaDB error
code (1264).
In addition it passes the strict mode up into the DML class to roll back
correctly.
It also sets the abort_on_warning flag for updates as this isn't set on
the rnd_init phase but is needed for strict mode to work.
> MCOL-129 INSERT/UPDATE strict mode support

- dbcon/joblist/jlf_execplantojoblist.cpp
For "select * from {view} where {col} in ({subquery})" type queries the
join for 'in' was being processed before any joins in the view. This
patch changes the priority so joins in views are processed first.
> MCOL-334 Give joins in views highest priority

- dbcon/mysql/ha_calpont_execplan.cpp
Appears to be a regression introduced in MCOL-361 which was causing a
segault with bug3670.negative.sql
> MCOL-385 Fix crash observed with 10.1.19 merge

- CMakeLists.txt
I accidentally used CMAKE_INSTALL_PREFIX which isn't always set for the
engine build. This patch uses INSTALL_ENGINE instead
> Fix rpath settings

- cpackEngineRPM.cmake
- dbcon/mysql/CMakeLists.txt
- dbcon/mysql/columnstore_info.sql
- dbcon/mysql/install_calpont_mysql.sh
- dbcon/mysql/is_columnstore_extents.cpp
- dbcon/mysql/is_columnstore_files.cpp
- oam/install_scripts/post-mysqld-install
- utils/idbdatafile/IDBFileSystem.h
- utils/idbdatafile/IDBPolicy.h
- utils/idbdatafile/PosixFileSystem.cpp
- utils/idbdatafile/PosixFileSystem.h
- utils/idbhdfs/hdfs-shared/HdfsFileSystem.cpp
- utils/idbhdfs/hdfs-shared/HdfsFileSystem.h
* Add INFORMATION_SCHEMA.COLUMNSTORE_FILES which contains information
about files
* Remove file information from COLUMNSTORE_EXTENTS (due to above)
* Hide columns with Object ID < 3000 (internal columns)
* Fix bad calculation in data_size columns
* Fix minor memory leak
* Add compressedSize() function to IDBFileSystem to get the used file
size for a compressed file
* Add columnstore_info schema with utility stored procedures to access
the information_schema tables
> MCOL-406 Improved Information Schema

- dbcon/mysql/columnstore_info.sql
- dbcon/mysql/is_columnstore_columns.cpp
- dbcon/mysql/is_columnstore_tables.cpp
- utils/idbdatafile/PosixFileSystem.cpp
- utils/idbhdfs/hdfs-shared/HdfsFileSystem.cpp
Fixes the following:
* Compression ratio calculation was incorrect
* Possible issues due to system catalog thread ID usage
* Compressed file size data count was leaking many FDs when the table
wasn't compressed
* Compressed file size data count was allocating random large amounts
of RAM and then leaking it when the table wasn't compressed
> MCOL-423 Fixes to I_S tables

- utils/mysqlcl_idb/state.cc
If there is only one packet in the buffer it is possible that the read
doesn't contain the whole packet, the resulting in the buffer pointer
going less than 0 and bad things happening.
> MCOL-433 Fix cross engine buffer underrun

- dbcon/joblist/crossenginestep.cpp
- dbcon/joblist/crossenginestep.h
Cross engine was using fRowGroupDelivered for pulling the rows out of
libdrizzle and passing them on to the next step in the job list
simultaneously on different threads. Sometimes this is OK, but with
larger data sets it leads to data corruption and race conditions.
For pulling the rows out of libdrizzle this patch uses a new RowGroup
object instead to avoid the collision.
In addition this patch makes the DrizzleMySQL class a dynamically
allocated object. A first step into potentially using unbuffered row
results for performance and lower RAM usage at a later date.
> MCOL-430 Fix memory corruption in cross-engine

- dbcon/mysql/columnstore_info.sql
table_usage() is now called using:
* table_usage(NULL, NULL) - all tables
* table_usage(NULL, 'table') - match tables with the name 'table' in all
schemas
* table_usage('schema', 'table') - match a specific schema and table
combination
> MCOL-406 add table_usage() schema input

- dbcon/mysql/ha_calpont_dml.cpp
When a table has 8 columns that could be NULL and a NOT NULL column
after the NULLable columns the check to see if we have gone over the
NULL bitmap byte limit is run prematurely trigging an error.
This patch moves the check to only run when we are looking at NULLable
columns.
> MCOL-457 Fix insert...select NULL bitmap

- utils/funcexp/func_mod.cpp
- utils/funcexp/functor_real.h
Func_mod uses double instead of int for char casting. This patch adds int
handling and uses it where appropriate.
> MCOL-389 Add int/string handling for mod()

- dbcon/mysql/ha_calpont_execplan.cpp
Fixes SUM() on constants and nested arithmetic inside aggregates.
> MCOL-301 fixes to aggregate functions

- dbcon/mysql/ha_calpont_execplan.cpp
It is possible for a BLOB/TEXT column to appear in a cross engine join.
This causes an ExeMgr crash later during execution. For now this patch
disable BLOB/TEXT support.
> MCOL-494 Don't try to process BLOB/TEXT

- oam/oamcpp/liboamcpp.cpp
- utils/common/cgroupconfigurator.cpp
- utils/configcpp/configcpp.cpp
- utils/rowgroup/rowgroup.cpp
This fix improves the performance of ExeMgr by doing the following:
* Significantly reduces the amount of time the xml configuration is
scanned
* Uses a much faster way to determine the CPU core count
* Reduces the amount of times certain allocations are executed
* Rowgroup pre-allocates vectors for 1024 rows
This improves performance for the first query of a connection and the
performance for smaller result sets. It may well improve performance in
other areas too.
> MCOL-505 Performance improvements to ExeMgr

- writeengine/splitter/we_sdhandler.cpp
The end of a cpimport adds a delay which is 1 second multiplied by the
number of PMs. This in-turn is multipled up with the number of
connections/threads causing a long delay when you have several PMs.
The delay is not required as we already have a 20ms delay and we will
re-enter the recv() if there is no data and we are still connected.
> MCOL-353 Fix lag at end of cpimport

- dbcon/mysql/is_columnstore_extents.cpp
Sometimes block offset can be > 0 but HWM can be 0 this causes a
calculation error in the DATA_SIZE field of I_S.columnstore_extents
> MCOL-454 Fix HWM edge case

- oam/install_scripts/binary_installer.sh
- oam/install_scripts/performance_installer.sh
- oam/install_scripts/user_installer.sh
- oamapps/postConfigure/postConfigure.cpp
Currently postConfigure requires deb or rpm packages to be copied on disk in /root
It also connect to each nodes using ssh to uninstall packages, push its own ones and install its own through expect scripts.
This makes MariaDB Columnstore very unfriendly with configuration management systems, and it's even worse with containers.
This patch aims to:
- add a new command line option to postConfigure: `-m` to tell postConfigure *not* to manage packages (default behaviour is still to manage them)
- pass a new option to expect scripts to reflect package management choice
- update expect scripts to respect this option
I have still to implement the same behaviour in one place at least: `processmanager.cpp` which check for package in `ProcessManager::addModule`.
I'll have a look at it asap.
Cheers
> Make packages management optional

- dbcon/joblist/crossenginestep.cpp
Use TCP instead of UDS for 'localhost' to keep behaviour the same as the
previous libdrizzle engine.
> MCOL-574 Fix cross engine for 'localhost'

- dbcon/mysql/is_columnstore_files.cpp
I_S.COLUMNSTORE_FILES now caches a connection per dbroot instead of
using a connection per file.
> MCOL-605 limit connections for I_S table

- writeengine/splitter/we_sdhandler.cpp
The end of a cpimport adds a delay which is 1 second multiplied by the
number of PMs. This in-turn is multipled up with the number of
connections/threads causing a long delay when you have several PMs.
The delay is not required as we already have a 20ms delay and we will
re-enter the recv() if there is no data and we are still connected.
> MCOL-611 backport of MCOL-353 Fix lag at end of cpimport

- CMakeLists.txt
Setting the RPATH to work with libmysqlclient broke it for everything
else. We now support both paths.
> MCOL-602 Fix RPATH

- dbcon/mysql/is_columnstore_files.cpp
The string stream which builds up the PM details wasn't cleared on each
run. This moves the creation of the string stream up to where it is
needed so a clean one is used each time.
> MCOL-605 Fix multi-node "Unkown error"

- dbcon/mysql/ha_calpont_execplan.cpp
SUM(1) behaviour was changed as part of MCOL-301. But the original
behaviour was correct.
> MCOL-653 Revert SUM(1) behaviour

- dbcon/mysql/is_columnstore_files.cpp
- utils/messageqcpp/CMakeLists.txt
- utils/messageqcpp/inetstreamsocket.cpp
- utils/messageqcpp/inetstreamsocket.h
- utils/messageqcpp/iosocket.h
- utils/messageqcpp/messagequeue.h
- utils/messageqcpp/messagequeuepool.cpp
- utils/messageqcpp/messagequeuepool.h
- utils/messageqcpp/socket.h
- versioning/BRM/dbrm.cpp
- versioning/BRM/masterdbrmnode.cpp
DBRM connections are reused so that we don't have a huge amount of
TIME_WAIT sockets when there are large amounts of DML. Also applied to
i_s.columnstore_files
> MCOL-529 Pool DBRM connections

- CMakeLists.txt
Makes it easier to debug user core files
> MCOL-655 Enable debug symbols on releases

- dbcon/execplan/calpontsystemcatalog.h
- dbcon/mysql/ha_calpont_dml.cpp
- writeengine/shared/we_type.h
* 64KB TEXT column had off-by-one length pointer counting
* TEXT I_S/LDI was looping where it shouldn't causing pointer issues
* TEXT data type wasn't fully understood by cpimport
> MCOL-669 TEXT cpimport fixes

- dbcon/mysql/ha_calpont_dml.cpp
BLOBs that are longer than half the maximum length of the column would
be turned into a negative length due to signed int casting. This would
cause them to turn into NULL inserts. Unsigned now used.
> MCOL-673 Fix I_S/LDI for larger BLOBs

- dbcon/execplan/predicateoperator.cpp
- dbcon/execplan/predicateoperator.h
- dbcon/joblist/groupconcat.cpp
- dbcon/joblist/jlf_common.cpp
- dbcon/joblist/jlf_execplantojoblist.cpp
- dbcon/joblist/jlf_subquery.cpp
- dbcon/joblist/jlf_tuplejoblist.cpp
- dbcon/joblist/lbidlist.cpp
- dbcon/joblist/passthrustep.cpp
- dbcon/joblist/rowestimator.cpp
- dbcon/joblist/subquerytransformer.cpp
- dbcon/joblist/tupleaggregatestep.cpp
- dbcon/joblist/tupleconstantstep.cpp
- dbcon/joblist/tupleunion.cpp
- dbcon/joblist/windowfunctionstep.cpp
- primitives/linux-port/column.cpp
- primitives/primproc/filtercommand.cpp
- utils/dataconvert/dataconvert.cpp
pDictionaryScan won't work for BLOB/TEXT since it requires searching the
data file and rebuilding the token from matches. The tokens can't be
rebuild correctly due the bits in the token used for block counts. This
patch forces the use of pDictionaryStep instead for WHERE conditions.
In addition this patch adds support for TEXT/BLOB in various parts of
the job step processing. This fixes things like error 202 during an
UPDATE with a join condition on TEXT/BLOB columns.
> MCOL-671 Fix TEXT/BLOB single row SELECT WHERE

- dbcon/joblist/expressionstep.cpp
- dbcon/joblist/jlf_tuplejoblist.cpp
If two tables have multiple joins and one of them was compatible then
the incompatible join detection would fail.
This patch moves the incompatible join detection so that every join is
checked. It also removes the incompatible join detection from
expressionstep as this is redundant and was causing some valid quries to
fail.
> MCOL-677 Fix incompatible join detection

- dbcon/mysql/ha_calpont_impl.cpp
MariaDB sends us a UTF8 length which we shortern because we think this
is a microsecond length. We need to keep this length.
> MCOL-683 Fix nested ADDDATE and DATE_FORMAT

- dbcon/mysql/ha_calpont_execplan.cpp
This was a hard coded limit due to StringStore not being able to handle
more than this. It restricts hex() unnecessarily and is now redundant.
> MCOL-697 Remove 64KB VARCHAR response limit

- dbcon/mysql/ha_calpont_execplan.cpp
For LONGBLOB the string return length was 4GB for functions which got
converted to -1 and then to 20. This patch sets it to just under 2GB
which we use for LONGBLOB everywhere else.
> MCOL-697 Limit the return length for LONGBLOB

- utils/joiner/tuplejoiner.cpp
It turns out not many machines have 32TB of RAM, so lets try not to
allocate that much for a LONGTEXT key join...
> MCOL-698 Fix joiner for LONGTEXT

- utils/joiner/tuplejoiner.cpp
Joins bigger than 64KB don't work and they would consume a lot of RAM if
they did, so error out if they are attempted.
> MCOL-698 Stop joins bigger than 64KB

- dbcon/joblist/expressionstep.cpp
- dbcon/joblist/jlf_execplantojoblist.cpp
Joins on BLOB columns aren't yet possible due to string pointers used.
This gives a meaningful error for it.
> MCOL-701 stop join on BLOB columns

- dbcon/joblist/jlf_execplantojoblist.cpp
The LIKE part of the query for non-dict CHAR/VARCHAR was converted to an
INT based on the length of the column. So on a 2 byte CHAR a LIKE of
'%05%' was truncated to '%0' which is a very different query. We should
not cast this to INT because we could use a LIKE of > 8 bytes on a
non-dict column. This patch turns LIKE into an expressionStep which
cater for longer strings rather than a simpleFilter.
> MCOL-656 Fix LIKE on non-dict CHAR/VARCHAR

- dbcon/joblist/groupconcat.cpp
- dbcon/joblist/limitedorderby.cpp
- dbcon/joblist/windowfunctionstep.cpp
ExeMgr uses ResourceManager to count memory usage. If a usage exceeded
error occurs the counting wasn't reset and subsequent usage attempts in
the same ExeMgr thread would error.
This patch moves the in-class accounting for GroupConcat and others so
that it happens before the error is detected. The memory usage counter
is then decremented correctly on the class destructor.
> MCOL-707 Fix ExeMgr's memory accounting

- utils/windowfunction/idborderby.cpp
Missed off window function order by memory accounting in my first commit
for MCOL-707. Fixed in the same way
> MCOL-707 Fix memory accounting for ORDER BY

- dbcon/joblist/crossenginestep.cpp
- dbcon/joblist/crossenginestep.h
We would get strange values for scale/precision in the results column of
a cross engine join causing bad results. This patch uses the values from
the libdrizzle client connector instead.
> MCOL-730 Fix decimals in cross engine join

- versioning/BRM/brmtypes.h
- versioning/BRM/masterdbrmnode.cpp
- versioning/BRM/masterdbrmnode.h
Added to DBRM master for use with the the new API so that it can get the
system catalog via the wire protocol.
> MCOL-739 Add command to get the system catalog

- dbcon/mysql/ha_calpont_impl.cpp
When some subquery changes were made over a year ago the flag to state
that an UPDATE subquery was not constant data was accidentally commented
out. This brings it back in again.
> MCOL-674 Fix subquery in UPDATE

- dbcon/mysql/ha_calpont_impl.cpp
Returns pointers to string buffer instead of making a copy first.
> MCOL-636 CHAR/VARCHAR return optimisation

- cpackEngineDEB.cmake
Debian 8 has Snappy in a different package name. In 1.1 we use the
distro version of Snappy so we have to check for this on package
building.
> MCOL-766 Fix Debian 8 building

- dbcon/joblist/crossenginestep.cpp
UTF8 characters just showed as question marks. This patch makes them
retrieve correctly.
> MCOL-830 Allow cross engine to work with UTF8

- dbcon/joblist/expressionstep.cpp
This check was removed but is actually still required in some cases.
> MCOL-840 Fix incompatible join on expression

- primitives/primproc/primitiveserver.cpp
ByteStream::advance can throw an exception if there isn't enough data in
the buffer yet. PrimProc's BPP processor would not catch this causing a
thread to be leaked every time. This was happening on BPP destroy and
abort.
> MCOL-857 Fix thread leak on ByteStream exception

- dbcon/joblist/crossenginestep.cpp
When subqueries and group by are used in CrossEngine the first row group
is either corrupted or ignored. This is related to MCOL-430 which fixed
the case for FE1 mode.
> MCOL-515 Fix cross engine for FE2/3 modes

- utils/rowgroup/rowgroup.cpp
The fix for MCOL-838 broke VARBINARY as it truncated on the first NUL on
StringStore deserialize. This fix uses append() to force a copy instead
whilst preserving length.
This fixes test012
> MCOL-858 Preserve NULs in StringStore deserialize

- dbcon/joblist/distributedenginecomm.cpp
It is possible that DistributedEngineComm can get the Stats object from
an MQE object and the MQE object freed before it's stats object is
passed to InetStreamSocket.
This patch makes sure that DistributedEngineComm gets a reference to MQE
instead of the pointer to the Stats object in another reference.
Therefore making sure that the Stats object still exists in
InetStreamSocket.
> MCOL-835 Fix use-after-free crash in ExeMgr

- primitives/primproc/batchprimitiveprocessor.cpp
- primitives/primproc/batchprimitiveprocessor.h
Whilst very rare we can hit a case where we attempt to unlock objLock
when it is already unlocked. With the Boost version in Ubuntu 16.04 this
triggers an abort() effectively crashing PrimProc.
In this patch we switch to a pthread mutex instead which does not have
this limitation. At a later date we can look into refactoring how BPP
and this mutex works.
> MCOL-744 Fix BPP mutex crash

- writeengine/wrapper/writeengine.cpp
We need to cast to a 64bit int, not a size based int.
> Fix write API char < 5

- dbcon/execplan/calpontsystemcatalog.cpp
- dbcon/execplan/calpontsystemcatalog.h
A race between a DDL change and a system catalog version cache update
can cause a deadlock in DDLProc. This change makes the mutex recursive.
> MCOL-859 DDL System catalog mutex deadlock

- dbcon/execplan/calpontsystemcatalog.cpp
- dbcon/execplan/calpontsystemcatalog.h
It is possible to have the columns for a table in a different order
within the system catalog. This causes problems for things like
WriteEngine so this patch sorts the columns based on position for the
system catalog cache.
> MCOL-895 Sort system catalog ridList

- dbcon/joblist/tupleaggregatestep.cpp
Aggregates could switch from unsigned to signed prior to execution. This
causes issues with NULL values since signed and unsigned NULLs are
different.
> MCOL-944 Fix aggregate type switch

- dbcon/joblist/crossenginestep.cpp
- dbcon/joblist/crossenginestep.h
If a CrossEngine step has multiple filters the filters were overwriting
each other. This fix stores the filters as a vector and processes them
in a loop.
> MCOL-662 Fix multiple filters in CrossEngine

- dbcon/mysql/ha_calpont_execplan.cpp
- utils/funcexp/func_cast.cpp
- utils/funcexp/funcexp.cpp
- utils/funcexp/functor_real.h
DOUBLE typecast was not supported and the failure detection caused a
crash.
This patch adds support for DOUBLE typecast and fixes the crash caused
when a non-supported function is detected as part of an arithmatic.
> MCOL-973 Fix DOUBLE typecast crash

- dbcon/mysql/my.cnf
- dbcon/mysql/mysql-Columnstore
- oam/etc/Columnstore.xml
- oam/install_scripts/CMakeLists.txt
- oam/install_scripts/mariadb-command-line.sh
- oam/install_scripts/master-rep-columnstore.sh
- oam/install_scripts/slave-rep-columnstore.sh
- oamapps/postConfigure/helpers.cpp
- oamapps/postConfigure/helpers.h
- oamapps/postConfigure/postConfigure.cpp
- procmgr/processmanager.cpp
- procmon/processmonitor.cpp
- procmon/processmonitor.h
change in ProcessMonitor.cpp to fix 1009, added new code to do the my.cnf changes via the mysql console and remove restarting of mysqld.
changes in ProcessMonitor.cpp for mcol-1014 - in the master-dist, master-rep, slave-dist, add checks to not send to PMs when to needed
change my.cnf, local query entty change to uncomment and assign as 0
change mysql-Columnstore - increase the start timeout for the stop waiting and also add where it will be the kill_by_pid when it fails to stops after waiting for the timeout period
Columnstore.xml changed ParentOam from unassigned to pm1
> mcol-1009 and mcol-1014

- dbcon/mysql/columnstore_info.sql
- dbcon/mysql/is_columnstore_extents.cpp
* COLUMNSTORE_EXTENTS data_size now shows the total size on the highest
segment of an extent file. It also shows 0 bytes if HWM is zero so that
if there is more than one segment it doesn't show 8192 bytes for the
lower segments.
* COMPRESSION_RATIO was missing some data and using compressed data size
instead of file size (which is probably more realistic).
> MCOL-1016 Fix I_S calculations

- writeengine/dictionary/we_dctnry.cpp
The signatures were getting destroyed whilst processing before being
used in the dictionary de-duplication cache making the cache full of
empty strings. This fix resets the signature after insertion for the
cache.
This fix also lets the signature cache be read when there is 1000
entries in it.
> MCOL-1021 Fix dictionary de-duplication cache

- dbcon/mysql/ha_calpont_dml.cpp
If a VARCHAR was defined as less than 255 characters and a data via LDI
or INSERT...SELECT was > 127 characters the length field would contain a
negative number.
In 1.0.11 and 1.1.0 this was not a problem because we cast the negative
back again. With MCOL-877 we stoped doing the double-cast. This patch
casts properly the first time.
> MCOL-1008 Fix bad length on bulk DML insert

- dbcon/mysql/ha_calpont_execplan.cpp
Cached conditions are things like (TRUE OR FALSE). They don't actually
add any value to the query and were breaking our working stack trying to
process them.
> MCOL-1029 Skip cached conditions

- dbcon/execplan/simplecolumn.cpp
Code appears to assume a simple returned column is derrived when that
may not always be the case.
> MCOL-1040 Fix returnedColumn assumption

- utils/funcexp/utils_utf8.h
- writeengine/bulk/we_bulkloadbuffer.cpp
- writeengine/dictionary/we_dctnry.cpp
cpimport would truncate UTF8 data half way through a character which
would cause problems for functions using that data. This patch
calculates the correct truncation point when inserting the data.
> MCOL-444 Truncate UTF8 correctly

- dbcon/mysql/columnstore_info.sql
* Uncompressed columns caused a miscalculation for compression ratio
* We now show a ratio such as 2:1 rather than a percentage
* compressed_data_size instead of file_size is used to show the
compression of actual data, ignoring the pre-allocated segment
> MCOL-1068 Improve compression_ratio() procedure

- utils/rowgroup/rowgroup.cpp
We should have been initalizing TEXT/BLOB 8 byte tokens for NULL,
instead we were initializing the entire length of the TEXT/BLOB which
can do a lot of damage.
> MCOL-1083 Fix NULL row init for TEXT/BLOB

- dbcon/mysql/ha_calpont.h
ColumnStore tables can have data modifications away from a specific
MariaDB server. This means it is possible for QCache to not be
invalidated properly in vtable mode 0. This patch makes sure it is
disabled for ColumnStore.
> MCOL-978 Disable QCache for ColumnStore

- dbcon/mysql/is_columnstore_files.cpp
If a dbroot is missing/offline mysqld would crash on
information_schema.columnstore_files due to not catching an exception.
This patch now catches the exception.
> MCOL-1116 Fix I_S.CS_FILES for missing dbroot

- CMakeLists.txt
- ddlproc/CMakeLists.txt
- ddlproc/ddlproc.cpp
- dmlproc/CMakeLists.txt
- dmlproc/dmlproc.cpp
- exemgr/CMakeLists.txt
- exemgr/main.cpp
- oamapps/serverMonitor/CMakeLists.txt
- oamapps/serverMonitor/main.cpp
- primitives/primproc/CMakeLists.txt
- primitives/primproc/primproc.cpp
- procmgr/CMakeLists.txt
- procmgr/main.cpp
- procmon/CMakeLists.txt
- procmon/main.cpp
- utils/common/crashtrace.cpp
- utils/common/crashtrace.h
- versioning/BRM/CMakeLists.txt
- versioning/BRM/masternode.cpp
- versioning/BRM/slavenode.cpp
- writeengine/server/CMakeLists.txt
- writeengine/server/we_server.cpp
This patch adds an automated crash dump which logs in
/var/log/mariadb/columnstore/trace/ when one of the ColumnStore daemons
crashes.
> MCOL-1085 Add crash dump to daemons

- dbcon/ddlpackage/CMakeLists.txt
- dbcon/ddlpackage/ddl.l
- dbcon/ddlpackage/ddl.y
- dbcon/mysql/ha_calpont_ddl.cpp
Both quotation types: grave accent ` and double quote " are supported. Bison parser outputs extra information if built in debug mode.
> MCOL-573. Reserverd words as table and column names.

- dbcon/mysql/ha_calpont_ddl.cpp
It occures, that major DDL/DML functions support a subset of UTF-8(according with [this](https://mariadb.com/kb/en/library/identifier-names/)) for table/column identifiers and only 'ALTER TABLE RENAME' doesn't support it because the mariadb plugin function ha_calpont_impl_rename_table_() replaces the initial query. I changed this and also replace push_warning() arguments according with recomendations given in server_code/sql/sql_error.cc to avoid possible sigabort.
Kindly take a look at the tiny [functional tests results](https://hastebin.com/bojufapave.vbs).
> MCOL-716 Support UTF-8 for table and column names.

- writeengine/wrapper/writeengine.cpp
- writeengine/wrapper/writeengine.h
When the API inserts data into ColumnStore which will roll over into a
new extent that data wasn't being put into the new extent and corruption
occured. This patch now tracks the additional data and inserts it into
the new extent. It also makes sure the LBIDs are stored so that they are
correctly committed.
> MCOL-1176 Fix API extent rollover

- dbcon/joblist/subquerytransformer.cpp
- dbcon/mysql/ha_calpont_execplan.cpp
When ExeMgr processes a correlated exists filter for a subquery inside a
view the de-duplication check doesn't work. We sometimes check unique
with the view name, sometimes not. We don't need the view name here so
remove it if we don't have it.
Also push the view name in the subquery.
> MCOL-1070 Fix exists in view subquery

- dbcon/mysql/columnstore_info.sql
The columnstore_info procs could only be called from within
columnstore_info due to them assuming format_filesize() is local. This
patch calls format_filesize() with an explicit schema allowing it to
work correctly.
> MCOL-1210 Allow procs to be called from any schema

- exemgr/main.cpp
A bad merge for in MCOL-1085 means that ExeMgr is missing the crash
handler. This adds it.
> Fix sig handler for ExeMgr

- dbcon/mysql/columnstore_info.sql
Dict size of 0 bytes returns NULL which means that the total count is 0.
This fix uses COALESCE to stop this happening.
> MCOL-1084 Fix TABLE_USAGE() when dict is 0 bytes

- dbcon/ddlpackageproc/altertableprocessor.cpp
CHANGE COLUMN was blocked for TEXT and BLOB types. This fix applies to
things like TINYTEXT as well as the only difference internally is the
column width.
> MCOL-1228 Allow alter table for TEXT/BLOB

- dbcon/ddlpackage/ddl.l
Object and column identifiers can start with a digit now.
> MCOL-1219: Object and column identifiers can start with a digit now.

- dbcon/joblist/lbidlist.cpp
- primitives/linux-port/column.cpp
- primitives/linux-port/dictionary.cpp
- utils/dataconvert/dataconvert.h
For equality string matches other engines ignore trailing whitespace
(this does not apply to LIKE matches). So we should do the same. This
patch trims whitespace for MIN/MAX extent elimination checks, fixed
width columns and dictionary columns during equality matches against
constants (SELECT * FROM t1 WHERE b = 'ABC').
> MCOL-1246 Fix string matching for whitespace

- dbcon/mysql/ha_calpont_execplan.cpp
Outer join handling inside views was broken due to the joins being
processed twice. This patch brings back the code so that outer joins in
views are only processed once.
> MCOL-1349 Fix outer joins in views

- dbcon/joblist/tupleunion.cpp
- utils/common/any.hpp
- utils/common/cgroupconfigurator.cpp
- utils/threadpool/threadpool.cpp
Ubuntu 18.04 uses GCC 7.3 which is a little stricter than before.
Fixes a few errors due to implicit includes that are no longer implicit
and a ton of warnings about the implied alignment of code in
utils/common/any.hpp
> MCOL-1376 Fix compiler errors in Ubuntu 18.04

- writeengine/splitter/we_cmdargs.h
- writeengine/splitter/we_filereadthread.cpp
- writeengine/splitter/we_filereadthread.h
- writeengine/splitter/we_sdhandler.cpp
- writeengine/splitter/we_sdhandler.h
It turns out -c wasn't actually connected to anything and now with have
BLOB/TEXT it is pretty useful. If -c is set to < 1MB then 1MB is used,
otherwise it will use the selected buffer size.
> MCOL-1197 Make -c work in cpimport

- dbcon/joblist/jlf_execplantojoblist.cpp
- dbcon/mysql/ha_calpont_execplan.cpp
This appears to be to fix equality matches in InfiniDB but at the same
time it breaks LIKE processing. Equality matching with trailing
whitespace was fixed in MCOL-1246 so the old InfiniDB patch can be
removed.
> MCOL-1403 Remove whitespace trimming on constants

- utils/funcexp/func_substring_index.cpp
If negative count number is more than the number of characters in the
string then it should always return the string.
For example if a table contains SUBSTRING_INDEX('zzz', 'z', -5) should
return 'zzz'. Before this patch it would return NULL.
> MCOL-1390 Fix SUBSTRING_INDEX for negative count

- utils/funcexp/func_hour.cpp
It is undocumented but when MariaDB gets a negative time in the HOUR()
function it always returns a positive value. This does the same for us.
> MCOL-807 HOUR() is always positive

- writeengine/wrapper/writeengine.cpp
Fixes the following:
* Generate error if calculateRowId fails
* No data written when first extent is completely full on a write, all
data going to second extent.
* 0 byte valArray malloc
* valArray free() on no malloc
* Column touched but no data written if all data going to second extent
* Wrong colWidth used on second extent calculateRowId
* Out of bounds memory write (crash) when no data for first extent
* Extent not committed if all data going to second extent
> MCOL-1408 Multiple API HWM boundary fixes

- primitives/primproc/primitiveserver.cpp
- utils/threadpool/prioritythreadpool.cpp
- utils/threadpool/prioritythreadpool.h
When an error occurs PriorityThreadPool could either cause PrimProc to crash or just completely ignore the problem and lose the job. This patch adds better error handling.
> MCOL-1474 Add error handling to PriorityThreadPool

- dbcon/mysql/columnstore_info.sql
- dbcon/mysql/is_columnstore_columns.cpp
- dbcon/mysql/is_columnstore_extents.cpp
- dbcon/mysql/is_columnstore_files.cpp
- dbcon/mysql/is_columnstore_tables.cpp
Add condition pushdowns to the information_schema tables to give a
performance improvement when a relevant WHERE condition is provided. In
addition there is a new table_usage() stored procedure designed to use
the pushdowns.
> MCOL-1484 I_S condition pushdowns

- exemgr/main.cpp
- primitives/primproc/primproc.cpp
- writeengine/server/we_server.cpp
Add a '-d' flag to WriteEngine, ExeMgr and PrimProc to let valgrind work
with them.
> MCOL-1330 Make debug flag let valgrind work

- CMakeLists.txt
More modern stack and bounds protection flags. Most won't activate until
GCC 8 is used but it makes us ready for that.
> MCOL-1378 Add more hardening flags

- dbcon/joblist/fifo.h
- primitives/linux-port/column.cpp
The FIFO buffer could get data in next() whilst a data swap is happening
due to a rare race condition. This patch adds mutexes around the parts
that could race.
The observed effect of this race was during a complex aggregate query
the results would occasionally be incorrect.
In addition this fixes a race condition in PrimProc's regex processor.
> MCOL-1037 Fix race condition in FIFO buffer

- dbcon/mysql/install_calpont_mysql.sh
The UDAF regr_avgx wasn't created because of an incorrect .so name used in the CREATE AGGREGATE FUNCTION statement.
> regr_agvx creation fix

- oam/install_scripts/post-install
- procmon/main.cpp
- procmon/processmonitor.cpp
We appear to chmod /dev/shm as a workaround to a CentOS 7 bug that was
fixed last year which accidentally set it to 755. If a user has /dev/shm
locked down we should get them to fix it rather than modifying it
ourselves.
The code before this fixed changed a root install to 755 for /dev/shm
which instantly broke anything using mmap() with MAP_SHARED as an
unprivileged user.
> MCOL-1579 Remove chmod of /dev/shm

- dbcon/mysql/ha_calpont_impl.cpp
Boost is taken out of global namespace to fix a conflict with MariaDB
10.3. This broke to_string in CentOS. Explicit namespace now used.
> MCOL-1653 Fix namespace issue

- dbcon/ddlpackage/ddl.y
- dbcon/mysql/ha_calpont_ddl.cpp
The code walks the source table meta-data structure to generate CREATE
table statement which creates the new table.
> Fix MCOL-1577 ColumnStore to allow CREATE TABLE table_name LIKE Syntax

- dbcon/ddlpackage/ddl.l
- dbcon/ddlpackage/ddl.y
MCOL-1660/1659 Table/column identifiers support spaces in DDL.
> MCOL-1660/1659 Table/column identifiers support spaces in DDL.

- ddlproc/ddlproc.cpp
- dmlproc/dmlproc.cpp
- dmlproc/dmlprocessor.cpp
- exemgr/main.cpp
This patch catches exceptions in DDLProc, DMLProc and ExeMgr which could
potentially happen during startup. Logging them instead of silently
ignoring them (or crashing in ExeMgr).
> MCOL-1694 & MCOL-1505 Improved exception handling

- dbcon/mysql/ha_calpont_execplan.cpp
A subquery could be marked as a CACHED_ITEM and need to be processed in column store.
> Mcol 1188 1.1

- primitives/blockcache/filebuffermgr.cpp
- writeengine/bulk/we_tableinfo.cpp
- writeengine/server/we_dmlcommandproc.cpp
- writeengine/shared/we_bulkrollbackmgr.cpp
This adds options which are user enabled to debug the LRU cache inside
ColumnStore. Specifically cache flushing.
It adds the following:
* PrimProc flush information when SIGUSR2 mode is enabled
* cpimport dictionary flush information when -d2 is used
* WriteEngineServer DML flush information to STDERR
> MCOL-1737 Add debug logging options for LRU cache

- dbcon/ddlpackage/ddl.l
- dbcon/ddlpackage/ddl.y
Since BOOLEAN is simply an alias for TINYINT(1), only the parser files are updated to add support for it in ColumnStore.
Am I missing something here?
> MCOL-266 Add support for BOOLEAN/BOOL data type

- tools/configMgt/autoConfigure.cpp
This patch makes sure the following settings are retained during an
upgrade:
* ThreadPoolSize
* TLSCS
* TLSClientCert
* TLSClientKey
> MCOL-1762 Keep Columnstore.xml settings

- utils/threadpool/threadpool.cpp
- utils/threadpool/threadpool.h
Anything that links against joblist will spin up a threadpool upon
startup. This includes the tools setConfig/getConfig. It is possible on
a low core count machine or low CPU speed that the signal to the prune
thread to shutdown is sent before the thread has completed startup when
these quick-running tools are used.
This fix adds a mutex so that spin up and shutdown can't happen at the
same time as well as a stop watch in case we are shutting down when
either the thread is running or we haven't fully started.
> MCOL-1810 Fix hang on low core count

- utils/funcexp/func_concat.cpp
- utils/funcexp/func_concat_ws.cpp
- utils/funcexp/func_elt.cpp
- utils/funcexp/func_insert.cpp
- utils/funcexp/func_repeat.cpp
- utils/funcexp/func_reverse.cpp
- utils/funcexp/functor_str.h
In the FLOAT/DOUBLE to string conversions a class global string was used
to store the result. Unfortunately it is possible for an instance of
this class to be used by multiple threads of PrimProc simultaneously.
This would cause a race and data corruption or more likely a crash.
This fix passes a string object from the caller to use instead.
> MCOL-1826 Fix race in FLOAT/DOUBLE to string

- dbcon/joblist/expressionstep.cpp
In 10.3 it gets renamed to octet_length()
> MCOL-1799 Fix length() with BLOB

- dbcon/mysql/install_calpont_mysql.sh
Escaped the ` chars to make the shell happy.
> MCOL-1654.  Querystats table creation broken.

- utils/libmysql_client/libmysql_client.cpp
- utils/libmysql_client/libmysql_client.h
If an error occurs in mysql_real_query() it fell through and tried to
get a result set anyway. This caused the MariaDB error message to be
forgotten and a generic one returned instead.
This fix returns the query error message and also uses the int error
code for generic errors instead of casting it to an unsigned int.
> MCOL-1885 Fix libmysql error handling

- utils/funcexp/func_concat_ws.cpp
There was a a bad line in some code that we don't currently compile. This
patch fixes that code in case we use it in the future.
> MCOL-1868 Fix error in unused code

- oam/install_scripts/pre-uninstall
- oamapps/postConfigure/mycnfUpgrade.cpp
- procmon/processmonitor.cpp
- versioning/BRM/save_brm.cpp
- versioning/BRM/slavecomm.cpp
https://jira.mariadb.org/browse/MCOL-1558
I see commit 65779c7 in this list right now.  That's part of another pull request & should be safe to ignore.  My fault, I forgot to put that change in its own feature branch.  I would suggest waiting for that PR to be merged before merging this one.
> Mcol 1558.  make the path stored in BRM_saves_current a relative path instead of an abs one.

- oam/install_scripts/pre-uninstall
- oamapps/postConfigure/mycnfUpgrade.cpp
Made it process the myCnf-include-args.text file the same way it does the other config files that get preserved across upgrades.
It's a quick impl, and it's functional but has one aesthetic shortcoming.  It will write a new merged copy of myCnf-include-args.text, where all of the comments have been alphabetized, and all of the options have been alphabetized.  If we want to not to make a jumble of any comments they've added, we can, but I suspect this is pretty unimportant.
> MCOL-1844.  Preserve user-added args in 'myCnf-include-args.text' across upgrades

- oam/etc/Columnstore.xml
- oam/etc/Columnstore.xml.singleserver
- primitives/primproc/primproc.cpp
Daniel suggested we re-use the NumBlocksPct config param to avoid headaches in support.  So now if the user specifies a 'm' or a 'g' suffix, it will be interpreted as mega/giga bytes.  Anything else (or nothing) will be interpreted as %age.
https://jira.mariadb.org/browse/MCOL-1847
> Mcol 1847 - absolute cache size option

- dbcon/mysql/ha_calpont_impl.cpp
This reverts commit 00ce77b742ce284d41cdce3b5a8a7ce2247bea52.
It does more harm than good on separate UM/PM servers.
> Revert MCOL-1624

- procmgr/processmanager.cpp
Made the BRM file copy stuff in procmgr handle absolute and relative paths.
> Mcol 1558 part 2.  Missed a necessary change
