- utils/funcexp/funchelpers.h
The value of a NULL pointer could potentionally be accessed
> MCOL-283 Fix mysql_calc_week

- utils/funcexp/func_monthname.cpp
Should return 0 to match MariaDB
> MCOL-332 Fix MONTHNAME() cast to double

- utils/funcexp/func_rand.cpp
Needs to be using 32bit ints to fully behave like MariaDB
> MCOL-326 Fix negative rand seeding

- utils/funcexp/func_math.cpp
Now throws an error instead of returning NULL to align with MariaDB
> MCOL-289 Fix MCOL(0) handling

- utils/funcexp/func_nullif.cpp
Comparing DATETIME with DATE compared two different date int formats
> MCOL-347 Fix NULLIF() for DATETIME with DATE

- CODING STANDARDS.md
- CONTRIBUTING.md
GitHub actually recommends reading them when opening pull requests so it
is good to have them in this tree too.
> Add contributing documents from the server tree

- dbcon/execplan/calpontsystemcatalog.cpp
- dbcon/mysql/ha_calpont_execplan.cpp
This is for better debuging for the bug. It doesn't fix the bug
> Add better cache explanations to debug_walk. This is debug only.

- dbcon/ddlpackageproc/droptableprocessor.cpp
Throw warning when table doesn't exist in columnstore so drop table if exists can still remove the front end table.
> Warning on drop table if exists error

- dbcon/mysql/columnstore_info.sql
Schema name should be included in results
> MCOL-406 Add schema to table_usage()

- dbcon/mysql/ha_calpont_ddl.cpp
Remove the hard-coded restriction in the DDL code, it isn't needed any
more
> MCOL-442 Allow default zero date/datetime

- dbcon/mysql/columnstore_info.sql
* Fix infinite loop problem when there are no ColumnStore tables
* Make table_usage('schema', NULL) work
> MCOL-406 More fixes to stored procs

- oamapps/mcsadmin/mcsadmin.cpp
Add support for dictionary OIDs.
Entering a table oid, or <schema><table> now lists all columns for the table.
> MCOL-451 add dictoid support and all columns for table oid

- utils/funcexp/functor_str.h
isnan requires std:: namespace
> MCOL-471 Fix GCC 6.3 support

- dbcon/ddlpackage/ddl.y
> MCOL-163 Add support for DOUBLE PRECISION

- dbcon/ddlpackageproc/altertableprocessor.cpp
Autoincrement range validation for ALTER TABLE
> MCOL-477 fix

- dbcon/ddlpackageproc/altertableprocessor.cpp
Autoincrement range validation for ALTER TABLE
> MCOL-477 fix for 1.0

- dbcon/mysql/columnstore_info.sql
The old procedure could be wildly incorrect when there were multiple
extents for a dictionary column.
The new one uses tables so that columnstore_files doesn't get
hammered too hard. They can't be temporary tables due to the reuse
restriction on temporary tables.
> MCOL-533 fix the table_usage() procedure

- dbcon/mysql/columnstore_info.sql
Calling from multiple connections simultaneously is bad. This adds a
lock preventing that.
> MCOL-533 Add lock to table_usage

- dbcon/joblist/CMakeLists.txt
- utils/querystats/CMakeLists.txt
Make linking with libmysqlclient work with out of tree builds
> MCOL-317 Fix out of tree builds

- cpackEngineRPM.cmake
Removed lib needs to be removed from RPM file list too
> MCOL-317 fix RPM building

- exemgr/main.cpp
- primitives/primproc/primproc.cpp
- writeengine/server/we_server.cpp
Especially for non-root installs. Otherwise we could be in for some pain
later...
> MCOL-553 Error if we can't set file limits

- oam/install_scripts/syslogSetup.sh
please review - just added the sudo to the systemctl commands
> MCOL-567 - added sudo to systemctl calls

- oam/install_scripts/binary_installer.sh
- oam/install_scripts/performance_installer.sh
- oam/install_scripts/user_installer.sh
- oamapps/postConfigure/installer.cpp
- oamapps/postConfigure/postConfigure.cpp
- procmgr/processmanager.cpp
First PR #123 was incomplete.
This one still is incomplete, but I made some progress :)
> Make packages management optional

- exemgr/main.cpp
- primitives/primproc/primproc.cpp
- writeengine/server/we_server.cpp
Now sends an error to the error log and aborts postConfigure
> MCOL-553 Improve error handling for ulimit

- dbcon/mysql/columnstore_info.sql
The fix for MCOL-533 accidentally removed units processing
> MCOL-533 fix units for table_usage

- dbcon/mysql/columnstore_info.sql
Backport MCOL-553 fixes to 1.0
> Mcol 533 1.0

- oam/install_scripts/columnstore
- oam/install_scripts/post-install
- procmon/main.cpp
- procmon/processmonitor.cpp
> MCOL-604 and MCOL-607 - change the chmod from 777 to 755

- oam/oamcpp/liboamcpp.cpp
- oamapps/postConfigure/postConfigure.cpp
- tools/setConfig/main.cpp
Reverts mariadb-corporation/mariadb-columnstore-engine#145
> revert MCOL-377

- primitives/primproc/dictstep.cpp
- writeengine/dictionary/we_dctnry.cpp
* Don't cache > 8000 bytes during update
* Fix PrimProc case where token is used more than once
> MCOL-670 Fix UPDATE with BLOB/TEXT

- dbcon/mysql/ha_calpont_execplan.cpp
BETWEEN was executing as a function on each row which meant that extent
elimination couldn't happen. We now execute as a predicate function
instead.
> MCOL-686 Fix BETWEEN performance

- utils/joiner/tuplejoiner.cpp
Joiner was thinking TEXT was INT
> MCOL-698 Fix joiner for TEXT columns

- dbcon/mysql/ha_calpont_execplan.cpp
BETWEEN was executing as a function on each row which meant that extent
elimination couldn't happen. We now execute as a predicate function
instead.
> MCOL-704 backport MCOL-686 Fix BETWEEN performance

- dbcon/mysql/ha_calpont_execplan.cpp
This converts <=> into "a = b OR (a IS NULL AND b IS NULL)"
> MCOL-657 Support the <=> operator

- writeengine/wrapper/writeengine.cpp
The column fill didn't detect that this was a TEXT/BLOB column.
> MCOL-710 Fix ALTER TABLE ADD COLUMN for TEXT/BLOB

- dbcon/execplan/aggregatecolumn.cpp
- utils/rowgroup/rowaggregation.cpp
> MCOL-712 Support TEXT for GROUP BY

- utils/funcexp/func_greatest.cpp
- utils/funcexp/func_least.cpp
- utils/funcexp/functor_all.h
Support was missing and int casting caused unexpected results
> MCOL-719 Add date/datetime to func_least/greatest

- oam/install_scripts/binary_installer.sh
- oam/install_scripts/columnstoreSyslog7
- oam/install_scripts/configReport.sh
- oam/install_scripts/module_installer.sh
- oam/install_scripts/performance_installer.sh
- oam/install_scripts/post-install
- oam/install_scripts/post-mysql-install
- oam/install_scripts/post-mysqld-install
- oam/install_scripts/pre-uninstall
- oam/install_scripts/remote_command.sh
- oam/install_scripts/remote_scp_get.sh
- oam/install_scripts/remote_scp_put.sh
- oam/install_scripts/rsync.sh
- oam/install_scripts/softwareReport.sh
- oam/install_scripts/syslogSetup.sh
- oam/install_scripts/user_installer.sh
- oamapps/columnstoreSupport/bulklogReport.sh
- oamapps/columnstoreSupport/configReport.sh
- oamapps/columnstoreSupport/hadoopReport.sh
- oamapps/columnstoreSupport/hardwareReport.sh
- oamapps/columnstoreSupport/logReport.sh
- oamapps/columnstoreSupport/resourceReport.sh
- oamapps/columnstoreSupport/softwareReport.sh
- utils/clusterTester/columnstoreClusterTester.sh
changes in script to use whoami instead of env $USER
> MCOL-702 / MCOL-368 - changed from builder to whoami

- primitives/primproc/primitiveserver.cpp
If ExeMgr disconnects (such as a crash) whilst queries are being
executed some BPP threads get orphaned. This patch tracks the BPP usage
for each threads and cleans up appropriately.
> MCOL-834 Cleanup BPP threads on ExeMgr disconnect

- primitives/primproc/batchprimitiveprocessor.cpp
- primitives/primproc/batchprimitiveprocessor.h
- primitives/primproc/primitiveserver.cpp
* Fix race condition in cleanup
* Fix mutex cleanup crash
> MCOL-834 Fix crashes introduced

- dbcon/execplan/simplefilter.cpp
Quote marks in cross engine where conditions need to be escaped
> MCOL-812 Escape cross engine filters

- dbcon/execplan/simplefilter.cpp
- dbcon/execplan/simplefilter.h
Previous attempt at fix only escaped quote
> MCOL-812 Escape slash as well as single quote

- primitives/primproc/batchprimitiveprocessor.cpp
- primitives/primproc/batchprimitiveprocessor.h
Whilst very rare we can hit a case where we attempt to unlock objLock
when it is already unlocked. With the Boost version in Ubuntu 16.04 this
triggers an abort() effectively crashing PrimProc.
In this patch we switch to a pthread mutex instead which does not have
this limitation. At a later date we can look into refactoring how BPP
and this mutex works.
> MCOL-744 Fix BPP mutex crash

- utils/rowgroup/rowgroup.cpp
- utils/rowgroup/rowgroup.h
StringStore as a vector of std::string had a performance regressions and
a rare crash.
This new version of StringStore restores the original StringStore with
the 64KB limitation and adds another vector to store strings that won't
fit into the small string storage.
> MCOL-874 StringStore Mk.3

- dbcon/mysql/ha_calpont_dml.cpp
Backslashes need escaping otherwise they are not sent to cpimport
correctly.
> MCOL-877 Fix I_S / LDI cpimport escaping

- writeengine/wrapper/writeengine.cpp
The rowID and therefore HWM for an insert was being calculated based on
the first column. If there are smaller columns in the table these will
insert in the middle of blocks instead of creating new blocks. This means
that we would no longer be crash safe and PrimProc gets very confused until
a cache flush.
We now use the smallest column to calculate the rowID and HWM increment
(as cpimport does).
> MCOL-984 Fix API bulk insert rowID/HWM calulation

- cpackEngineRPM.cmake
- oam/install_scripts/CMakeLists.txt
- oam/install_scripts/mariadb-command-line.sh
- oamapps/postConfigure/helpers.cpp
- procmgr/processmanager.cpp
- procmon/processmonitor.cpp
- procmon/processmonitor.h
back ported 1,1 mysql replication fixes..
1. changed all checks where it checks for pm node updating or not
2. add new script mariadb-command-line.sh
> MCOL-942 - backported mysql rep fixes from 1.1

- dbcon/ddlpackage/CMakeLists.txt
- dbcon/dmlpackage/CMakeLists.txt
I added custom target that depends on generated files to get over with the [warnings](https://hastebin.com/dutetipuki.rb) so please take a look at it.
> MCOL-548. Remove cmake warnings.

- oam/etc/Columnstore.xml
- oam/etc/Columnstore.xml.singleserver
- oam/oamcpp/liboamcpp.h
- oamapps/alarmmanager/alarmglobal.h
- oamapps/alarmmanager/alarmmanager.cpp
- oamapps/alarmmanager/alarmmanager.h
- oamapps/postConfigure/postConfigure.cpp
- procmgr/main.cpp
- procmgr/processmanager.cpp
- procmgr/processmanager.h
- procmon/main.cpp
- tools/configMgt/autoConfigure.cpp
fixed both 1185 and 436..
1. all alarm set/clear request sent to procmgr
2. procmgr now has a dedicated port to receive and serially process alarm request. this will prevent the file corruption issue.
> Mcol 1185 and mcol 436

- dbcon/ddlpackage/ddl.y
- dbcon/mysql/ha_calpont_ddl.cpp
Here are the results of the [tests](https://hastebin.com/onaniyikox.cs).
> MCOL-876. CS now supports RENAME TABLE sql statement. 

- dbcon/mysql/ha_calpont_execplan.cpp
An unneeded change from the fix for MCOL-1070 that broke vTpch01b.sql
> Fix view alias regression

- writeengine/splitter/we_sdhandler.cpp
Replace InfiniDB with Columnstore in the returned message.
> MCOL-1002. Replace InfiniDB with Columnstore in the returned message.

- dbcon/execplan/arithmeticoperator.cpp
- dbcon/execplan/filter.cpp
- dbcon/execplan/logicoperator.cpp
- dbcon/execplan/predicateoperator.cpp
- dbcon/execplan/simplecolumn.cpp
- dbcon/execplan/treenodeimpl.cpp
- dbcon/mysql/ha_calpont_execplan.cpp
Change the way buildCaseFunction() handles the ptWorkStack and the rcWorkStack.
> MCOL-1234 Nested CASE filters not processed

- dbcon/joblist/jlf_execplantojoblist.cpp
Cross engine step needs the filters for joining a constant with the
cross engine table. Deleting them early causes a crash.
> MCOL-1182 Keep filters for cross engine step

- dbcon/joblist/tupleaggregatestep.cpp
> MCOL 1348 ExeMgr processes SELECT with UDAF, intermingled with other projections.

- utils/rowgroup/rowgroup.cpp
- utils/rowgroup/rowgroup.h
StringStore originally worked by returning a 32bit pointer to a memory
location and storing the length with that pointer. This allowed 4GB to
be stored in 64KB blocks. With 1.1 we used the high bit to signify a
TEXT/BLOB string of > 64KB reducing the max capacity to 2GB but without
any bounds checking.
So, if you went over the 2GB mark the getter would think you are trying
to get a long string instead of a short one and come up empty. It would
then return NULL.
This patch uses 64bit memory points still retaining the high bit to
signify long strings. It also now stores the length with the string
rather than with the pointer to allow the full 64bits for pointers.
It also adds a bounds check for small strings.
> MCOL-1396 Allow StringStore to hold more than 2GB

- utils/dataconvert/dataconvert.cpp
- utils/funcexp/func_add_time.cpp
The changes to addtime/subtime for TIME datatype broke the handling of
the adding and subtracting of time. This fixes that.
> MCOL-1402 Fix addtime/subtime

- dbcon/joblist/tupleunion.cpp
- utils/common/any.hpp
- utils/common/cgroupconfigurator.cpp
- utils/threadpool/threadpool.cpp
Backport Ubuntu 18.04 support to 1.1
> MCOL-1412 Ubuntu 18.04 support

- dbcon/ddlpackage/ddl.y
Fixed regression with extra spaces after dot in qualified identifiers.
> MCOL-1415 

- dbcon/ddlpackage/ddl.l
- dbcon/ddlpackage/ddl.y
- dbcon/mysql/ha_calpont_ddl.cpp
The feature includes support for reserved words used as a column name.
> MCOL-1384 Backport MCOL-573 to 1.1 

- dbcon/joblist/crossenginestep.cpp
- dbcon/joblist/crossenginestep.h
Now shows MariaDB error code and message where possible.
> MCOL-1475 Improve cross engine error handling

- utils/joiner/tuplejoiner.cpp
Found using -D_GLIBCXX_ASSERTIONS
> MCOL-1496 Fix array bug in joiner

- .gitignore
- dbcon/mysql/ha_calpont_execplan.cpp
- procmgr/processmanager.cpp
Added /.idea to ignore files generated by CLion IDE.
> Fix MCOL-1155 to correctly process the NOT subtree.

- utils/funcexp/func_cast.cpp
- utils/funcexp/func_date.cpp
- utils/funcexp/func_date_format.cpp
- utils/funcexp/func_makedate.cpp
- utils/funcexp/func_nullif.cpp
- utils/funcexp/func_timediff.cpp
- utils/funcexp/func_to_days.cpp
Fixes the following:
* CAST() (as DATE/DATETIME)
* DATE()
* DATE_FORMAT()
* MAKEDATE()
* NULLIF()
* TIMEDIFF()
* TO_DAYS() / DATEDIFF()
> MCOL-1433 Fix some functions for TIME

- dbcon/execplan/calpontselectexecutionplan.h
- dbcon/joblist/joblistfactory.cpp
- dbcon/mysql/ha_calpont.cpp
- dbcon/mysql/ha_calpont.h
- dbcon/mysql/ha_calpont_execplan.cpp
- dbcon/mysql/ha_calpont_impl.cpp
- dbcon/mysql/ha_calpont_impl_if.h
Aggregates could be used as function arguments in projection e.g. sum(i)+1. Also refactored LIMIT processing in getGroupPlan().
> Fixes for MCOL-1510, MCOL-1520

- config.h.cmake
- configureEngine.cmake
- exemgr/main.cpp
- oam/oamcpp/liboamcpp.cpp
- oam/oamcpp/oamcache.cpp
- writeengine/redistribute/we_redistributecontrolthread.cpp
- writeengine/splitter/we_sdhandler.cpp
Squashed commit of the following:
commit faaee9141af019363cbe207e4cdbe01e01493d0f
Author: Patrick LeBlanc <patrick.leblanc@mariadb.com>
Date:   Wed Oct 3 13:03:02 2018 -0500
Commented a debugging printout.
commit e47e784c53705463696916f5c8dae1c014732f77
Author: Patrick LeBlanc <patrick.leblanc@mariadb.com>
Date:   Wed Oct 3 12:13:23 2018 -0500
Moved the SKIP_OAM_INIT check for cleanliness, added 'config.h' to
other places that need it.
commit 662604553538795f9a03e1167c7b44376349a56a
Author: Patrick LeBlanc <patrick.leblanc@mariadb.com>
Date:   Tue Oct 2 16:33:06 2018 -0500
WIP.  First cut of excising OAM and root access from the dev process.
This passes most tests; need to make sure that the tests that fail
have nothing to do with this change.
DMLProc is doing something that results in a …
> Squash commit of fix-skip-oam-init branch.

- utils/funcexp/func_makedate.cpp
- utils/funcexp/func_timediff.cpp
Fix saturation behaviour for TIME with MAKEDATE() and TIMEDIFF()
> MCOL-1433 Fix TIME for MAKEDATE/TIMEDIFF

- writeengine/bulk/we_bulkloadbuffer.cpp
This also adds support for MCOL-266 in cpimport.
> MCOL-1786 Handle "true" keyword for numeric data types in cpimport

- dbcon/mysql/ha_calpont_execplan.cpp
Somehow some dead code came back. It is dead again now.
> MCOL-1776 Fix MCOL-1403 regression

- dbcon/mysql/ha_calpont.cpp
The server won`t use GROUP BY handler in queries with:	
unsupported JOIN types
impossible HAVING
impossible WHERE
> MCOL-1519 GROUP BY doesn't process unsupported queries.

- dbcon/mysql/ha_calpont_ddl.cpp
RENAME doesn`t work with tables whose names contains special or non-ASCII chars. 
The commit alters ha_calpont_impl_rename_table_() to decode paths received from the server.
> MCOL-1855 RENAME TABLE now supports tablenames with non-alphanumerical chars.

- oam/etc/Columnstore.xml
- oam/etc/Columnstore.xml.singleserver
- primitives/primproc/primproc.cpp
https://jira.mariadb.org/browse/MCOL-1847
> Mcol 1847.  Added ability to specify an absolute value for PM cache size

- dbcon/mysql/ha_calpont_execplan.cpp
MariaDB added a generic way to detect case type so remove our hack and
switch to that.
> MCOL-1790 Switch to MariaDB's case type detection
